# Linear Regression

In [1]:
import pandas as pd
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

## Profit based on R&D Spend, Administration and Marketing Spend

In [2]:
data = pd.read_csv('50_Startups.csv')
data.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [3]:
X = data[['R&D Spend','Administration','Marketing Spend']].values
Y = data['Profit'].values
X , Y 

(array([[165349.2 , 136897.8 , 471784.1 ],
        [162597.7 , 151377.59, 443898.53],
        [153441.51, 101145.55, 407934.54],
        [144372.41, 118671.85, 383199.62],
        [142107.34,  91391.77, 366168.42],
        [131876.9 ,  99814.71, 362861.36],
        [134615.46, 147198.87, 127716.82],
        [130298.13, 145530.06, 323876.68],
        [120542.52, 148718.95, 311613.29],
        [123334.88, 108679.17, 304981.62],
        [101913.08, 110594.11, 229160.95],
        [100671.96,  91790.61, 249744.55],
        [ 93863.75, 127320.38, 249839.44],
        [ 91992.39, 135495.07, 252664.93],
        [119943.24, 156547.42, 256512.92],
        [114523.61, 122616.84, 261776.23],
        [ 78013.11, 121597.55, 264346.06],
        [ 94657.16, 145077.58, 282574.31],
        [ 91749.16, 114175.79, 294919.57],
        [ 86419.7 , 153514.11,      0.  ],
        [ 76253.86, 113867.3 , 298664.47],
        [ 78389.47, 153773.43, 299737.29],
        [ 73994.56, 122782.75, 303319.26],
        [ 6

In [4]:
x_train, x_test, y_train, y_test = train_test_split(X, Y, train_size=0.8, test_size=0.2, random_state=23)
# x_train=x_train.reshape(-1,1)
# x_test=x_test.reshape(-1,1)

## Creating the linear regression model

In [5]:
model = LinearRegression()
model.fit(x_train, y_train)
model.score(X, Y)

0.9502508548484838

## Predict output based on Regression Model

In [6]:
y_predict = model.predict(x_test)
# y_predict , y_test , x_test
df = pd.DataFrame({'Actual': y_test, 'Predicted': y_predict})
df

Actual      Predicted
0  132602.65  150689.285330
1  124266.90  129099.549736
2  125370.37  130477.327582
3   97427.84   99816.732113
4  134307.35  127863.044904
5   96778.92   97478.084291
6  118474.03  116283.362778
7  152211.77  152560.230113
8   90708.19   74240.904290
9  103282.38  102202.991288

## Calculating the accuracy

In [7]:
train_accuracy = model.score(x_train, y_train)
test_accuracy = model.score(x_test, y_test)
train_accuracy , test_accuracy

(0.9569214330304159, 0.8038377917488992)

## Give a specific R&D Spend and see the result

In [8]:
new_data = np.array([[10,5,2]])
new_data

array([[10,  5,  2]])

In [9]:
model.predict(new_data)

array([49304.06769999])

## Plotting

* It didn't work yet

In [10]:
# X = data[['R&D Spend','Administration','Marketing Spend']].sum(axis=1).values.reshape(-1,1)
# Y = data['Profit'].values.reshape(-1,1)
# x_train, x_test, y_train, y_test = train_test_split(X, Y, train_size=0.8, test_size=0.2, random_state=23)
# plt.scatter(x_test,y_test,color='blue')
# plt.scatter(x_test,y_predict,color='red')
# plt.xlabel('Years of Experience')
# plt.ylabel('Salary')
# plt.title('Salary Data')